config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
 
  root 'fiscal_years#index'
  # Custom route for logging in
  get 'login', to: 'sessions#new'
  post 'login', to: 'sessions#create'
  delete 'logout', to: 'sessions#destroy'

  resources :companies, only: [] do
    resources :fiscal_years, only: [:index] do
      resources :monthly_reports, only: [:index], shallow: true do
        resources :expense_revenues, only: [:index]
      end
    end
  end

  resources :categories, only: [:index, :show]

  
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/category.rb
class Category < ApplicationRecord
    has_many :expense_revenues, dependent: :destroy
    validates :name, presence: true, uniqueness: true
  end
  

app/models/company.rb
class Company < ApplicationRecord
    has_secure_password
    has_many :fiscal_years, dependent: :destroy
    validates :name, :email, presence: true
    validates :email, uniqueness: true
  end
  

app/models/expense_revenue.rb
class ExpenseRevenue < ApplicationRecord
  belongs_to :monthly_report
  belongs_to :category
  validates :amount, presence: true
end

app/models/fiscal_year.rb
class FiscalYear < ApplicationRecord
  belongs_to :company
  has_many :monthly_reports, dependent: :destroy
  validates :year, presence: true
end

app/models/monthly_report.rb
class MonthlyReport < ApplicationRecord
  belongs_to :fiscal_year
  has_many :expense_revenues, dependent: :destroy
  validates :month, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
end

app/controllers/companies_controller.rb
class CompaniesController < ApplicationController
end

app/controllers/expense_revenues_controller.rb
class ExpenseRevenuesController < ApplicationController
    before_action :set_monthly_report
  
    def index
      @monthly_report = MonthlyReport.find(params[:monthly_report_id])
      @fiscal_year = @monthly_report.fiscal_year
      @expense_revenues = @monthly_report.expense_revenues
    end
  
    private
  
    def set_monthly_report
      @monthly_report = MonthlyReport.find(params[:monthly_report_id])
    end
  end
  

app/controllers/fiscal_years_controller.rb
class FiscalYearsController < ApplicationController
    before_action :set_company
    before_action :require_login
  
    def index
      @fiscal_years = @company.fiscal_years
    end
  
    private
  
    def set_company
      @company = Company.find(session[:company_id])
    end
    

    def require_login
        unless session[:company_id]
          flash[:error] = "You must be logged in to access this section"
          redirect_to login_path
        end
      end
  end
  

app/controllers/monthly_reports_controller.rb
class MonthlyReportsController < ApplicationController
    before_action :set_fiscal_year
  
    def index
      @monthly_reports = @fiscal_year.monthly_reports
    end
  
    private
  
    def set_fiscal_year
      @fiscal_year = FiscalYear.find(params[:fiscal_year_id])
    end
  end
  

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
include SessionsHelper
  def new
  end

  # def create
  #   company = Company.find_by(email: params[:session][:email])
  #   if company && company.authenticate(params[:session][:password])
  #     log_in company
  #     respond_to do |format|
  #       format.turbo_stream { turbo_stream.replace "login_form", partial: "sessions/empty" }
  #       format.html { redirect_to root_path }
  #     end
  #   else
  #     flash.now[:danger] = "Invalid email/password combination"
  #     render "new"
  #   end
  # end

  def create
    company = Company.find_by(email: params[:session][:email])
    if company && company.authenticate(params[:session][:password])
      log_in company
      redirect_to root_path
    else
      flash.now[:danger] = 'Invalid email/password combination'
      render 'new'
    end
  end
  
  

  def destroy
    log_out
    redirect_to root_url
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
    def month_name(month_number)
      Date::MONTHNAMES[month_number]
    end
  end
  

app/helpers/sessions_helper.rb
module SessionsHelper
    # Logs in the given company.
    def log_in(company)
      session[:company_id] = company.id
    end
  
    # Logs out the current company.
    def log_out
      session.delete(:company_id)
      @current_company = nil
    end
  
    # Returns the current logged-in company (if any).
    def current_company
      @current_company ||= Company.find_by(id: session[:company_id])
    end
  
    # Returns true if the company is logged in, false otherwise.
    def logged_in?
      !current_company.nil?
    end
  end
  

app/views/categories/index.html.erb
<h1>Categories</h1>

<% @categories.each do |category| %>
  <div>
    <%= link_to category.name, category_path(category) %>
  </div>
<% end %>

app/views/categories/show.html.erb
<h1><%= @category.name %></h1>

<p>Category details...</p>

app/views/expense_revenues/index.html.erb
<div class="container">
  <h1>Expense Revenues for <%= Date::MONTHNAMES[@monthly_report.month] %> <%= @fiscal_year.year %></h1>

  <table class="table">
    <thead>
      <tr>
        <th scope="col">Category</th>
        <th scope="col">Amount</th>
      </tr>
    </thead>
    <tbody>
      <% @expense_revenues.each do |expense_revenue| %>
        <tr>
          <td><%= expense_revenue.category.name %></td>
          <td><%= number_to_currency(expense_revenue.amount) %></td>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>

app/views/fiscal_years/index.html.erb
<div class="row">
  <div class="col-md-6 offset-md-3">
    <h1 class="text-center">Fiscal Years</h1>
    <table class="table table-bordered table-hover">
      <thead>
        <tr>
          <th>Year</th>
          <th>Actions</th>
        </tr>
      </thead>
      <tbody>
        <% @fiscal_years.each do |fiscal_year| %>
          <tr>
            <td><%= fiscal_year.year %></td>
            <td><%= link_to 'View Monthly Reports', company_fiscal_year_monthly_reports_path(@company, fiscal_year) %></td>
          </tr>
        <% end %>
      </tbody>
    </table>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Accounting</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <nav class="navbar navbar-expand-lg navbar-light bg-light">
      <div class="container">
        <a class="navbar-brand" href="#">Accounting</a>
        <div class="collapse navbar-collapse">
          <ul class="navbar-nav ms-auto">
            <% if session[:company_id] %>
              <li class="nav-item">
                <span class="nav-link">Logged in as: <%= Company.find(session[:company_id]).name %></span>
              </li>
              <li class="nav-item">
                <%= link_to "Logout", logout_path, method: :delete, class: "nav-link" %>
              </li>
            <% else %>
              <li class="nav-item">
                <%= link_to "Login", login_path, class: "nav-link" %>
              </li>
            <% end %>
          </ul>
        </div>
      </div>
    </nav>

    <div class="container">
      <%= yield %>
    </div>
  </body>
</html>

app/views/monthly_reports/index.html.erb
<div class="container">
  <h1>Monthly Reports for <%= @fiscal_year.year %></h1>

  <table class="table">
    <thead>
      <tr>
        <th scope="col">Month</th>
        <th scope="col">Action</th>
      </tr>
    </thead>
    <tbody>
      <% @monthly_reports.each do |monthly_report| %>
        <tr>
          <td><%= Date::MONTHNAMES[monthly_report.month] %></td>
          <td><%= link_to 'View Details', monthly_report_expense_revenues_path(monthly_report, fiscal_year: @fiscal_year), class: "btn btn-primary" %></td>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>